import { randomBytes } from "node:crypto";
import { NextResponse } from "next/server";
import { CSRF_COOKIE } from "@/lib/csrf-constants";
import { SESSION_COOKIE, sessionCookieOptions } from "@/lib/session-config";
import { assertCsrfToken, assertMutationOrigin } from "@/lib/csrf";
function expectedOrigin():string { if(!process.env.APP_ORIGIN) throw new Error("APP_ORIGIN is required"); return process.env.APP_ORIGIN; }
function backendUrl(path:string):string { const base=process.env.CALLPULSE_API_URL; if(!base) throw new Error("CALLPULSE_API_URL is required"); return `${base.replace(/\/$/,"")}${path}`; }
export async function POST(request:Request) { assertMutationOrigin(request,expectedOrigin()); const body=await request.json(); const response=await fetch(backendUrl("/auth/login"),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body),cache:"no-store"}); if(!response.ok) return NextResponse.json({detail:"Unable to sign in"},{status:response.status}); const payload=await response.json() as {access_token?:string}; if(!payload.access_token) return NextResponse.json({detail:"Invalid authentication response"},{status:502}); const csrf=randomBytes(32).toString("base64url"); const result=NextResponse.json({authenticated:true}); result.cookies.set(SESSION_COOKIE,payload.access_token,sessionCookieOptions); result.cookies.set(CSRF_COOKIE,csrf,{secure:sessionCookieOptions.secure,sameSite:"lax",path:"/"}); return result; }
export async function DELETE(request:Request) { assertMutationOrigin(request,expectedOrigin()); const cookieHeader=request.headers.get("cookie")??""; const csrf=cookieHeader.match(/(?:^|; )callpulse_csrf=([^;]+)/)?.[1]; assertCsrfToken(request,csrf?decodeURIComponent(csrf):undefined); const session=cookieHeader.match(/(?:^|; )__Host-callpulse_session=([^;]+)/)?.[1]; if(session){await fetch(backendUrl("/auth/logout"),{method:"POST",headers:{authorization:`Bearer ${decodeURIComponent(session)}`},cache:"no-store"});} const result=NextResponse.json({authenticated:false}); result.cookies.delete(SESSION_COOKIE); result.cookies.delete(CSRF_COOKIE); return result; }
